### ISSUE TITLE
Help listing Unapproved devices (pending,declined)

### ISSUE THREAD

**Issue by Jarli01** [homotechsual/NinjaOne#10]
Hey @homotechsual hope I'm not a bother yet, and I hope you don't mind. 

I'm working to try and pull a list of devices in a status other than Approved and while I don't believe this is a limit on this PS Module (and I'm leaning towards it being a NRMM issue I wanted confirmation). Can you look at the below and tell me if I'm wrong here and just doing something wrong?

![image](https://user-images.githubusercontent.com/14837699/173611258-bf85f6db-a020-4bc0-bd53-f9db1fd67082.png)

![image](https://user-images.githubusercontent.com/14837699/173611279-f5c59b13-334c-48ec-b2f4-bf00b846fc92.png)

I have a running topic in their DOJO community as well, https://ninjarmm.zendesk.com/hc/en-us/community/posts/6908556140557-Ninja-API-Pending-Device-list

**Comment by homotechsual** [comment]
Documentation for `deviceFilter`: https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf

**Comment by Jarli01** [comment]
OH. . . so much easier than I was doing. 

Thanks!

**Comment by Jarli01** [comment]
That's nice! will have to start using that, next on my list is to convert OrganizationID to Organization Name for this report

**Comment by homotechsual** [comment]
`(Get-NinjaOneOrganisations -organisationId $id).name`
