### ISSUE TITLE
Get-NinjaOneDevices -deviceFilter "status=pending" only shows workstations

### ISSUE THREAD

**Issue by Jarli01** [homotechsual/NinjaOne#12]
@homotechsual I'm sure this isn't an issue on your side, but can you check to see if you only get workstations listed in these results?

![image](https://user-images.githubusercontent.com/14837699/173863660-cbf962f1-828a-41e7-83f4-4fd27b396186.png)

I know there are severs in a pending status that don't appear (as shown in the above screenshot) and wanted confirmation.

**Comment by homotechsual** [comment]
So this works for me:

![image](https://user-images.githubusercontent.com/2288257/174033418-fa8cd028-adce-4d65-b47f-a180c01889b7.png)

**Comment by homotechsual** [comment]
The `AND` needs to be all capitals.

**Comment by Jarli01** [comment]
Hrm I get 500 Internal Server error. . . 

![image](https://user-images.githubusercontent.com/14837699/174064484-7b1bb521-6144-4db5-9131-16a5dc6a190d.png)

**Comment by homotechsual** [comment]
Status value is also all capitals. `PENDING` not `Pending`

**Comment by Jarli01** [comment]
Where as any individual filter seems to work, class=WINDOWS_SERVER or status=Pending (or the PENDING)

I thought about capitol as well, but it didn't seem to make a change. . .

![image](https://user-images.githubusercontent.com/14837699/174064828-334e7707-30bd-4c98-8c24-d544a75df4c9.png)

**Comment by Jarli01** [comment]
client credentials as that was the only thing that seemed to work from my prior ticket here. 

![image](https://user-images.githubusercontent.com/14837699/174065489-ef0cc43e-8100-4cba-90c6-1017667dd860.png)

**Comment by homotechsual** [comment]
this is very odd - I can do that request with `client_credentials` auth and it works fine. Probably one for `api@ninjarmm.com` there.

**Comment by homotechsual** [comment]
First though let's rule out any weirdness can you copy/paste this:

```ps
Get-NinjaOneDevices -deviceFilter "status=PENDING AND class=WINDOWS_SERVER" | ft
```

**Comment by homotechsual** [comment]
If you remove the `| ft` any change?

**Comment by Jarli01** [comment]
No, just a new line return for the next command.

**Comment by Jarli01** [comment]
If I filter with "class=WINDOWS_SERVER" I get details, but only for Approved devices, nothing pending.

**Comment by homotechsual** [comment]
Very strange, definitely one for support!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 E ***@***.***
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.

**Comment by Jarli01** [comment]
That is what I thought, thanks, I'll open the case with support.
