### ISSUE TITLE
Ticketing functions not working for me

### ISSUE THREAD

**Issue by notadevcollins** [homotechsual/NinjaOne#14]
First off thank you so much for this work!

I can get most "GET" functions to work as expected except for the ticket functions I get 

> The NinjaOne API said FAILURE: NullPointerException. The API returned the following HTTP error response: 500 Internal Server Error

when I try to run `Get-NinjaOneTicketLogEntries -ticketID '1014'` same if I leave off the ticketid and respond to the prompt in the script 

in the ninja documentation it looks like you have to now specify another field like description, this is the url that the documentation spit out to me https://app.ninjarmm.com/v2/ticketing/ticket/1014/log-entry?type=DESCRIPTION  I try to do an invoke-webrequest with this url but this api is over my head and I have no idea what i'm doing,

I just want to pull out ticket details so I can generate an invoice for work done

Thank you for any help!

**Comment by homotechsual** [comment]
Are you using Client Credentials authentication?

**Comment by notadevcollins** [comment]
yes, I believe so , when I run Get-NinjaOneContacts or a similar command it works as expected, this is what i'm trying to run

$ConnectionParameters = @{
    Instance = 'us'
    ClientID = 'myActualID'
    ClientSecret = 'myActualSecret'
    UseClientAuth = $True
}

Connect-NinjaOne @ConnectionParameters
Get-NinjaOneTicketLogEntries -ticketID '1014'

**Comment by homotechsual** [comment]
Ticketing endpoints still have major issues with Client Credentials auth. Currently the recommendation is to use `Code` auth flows unfortunately.

Ping your account manager and `api@ninjarmm.com` and let them know that this is important for you.

**Comment by homotechsual** [comment]
With `Code` auth:

![image](https://user-images.githubusercontent.com/2288257/187283885-f7087cd4-a43b-405b-928a-b04acad77786.png)

**Comment by notadevcollins** [comment]
will do, Thank you so much for this project

**Comment by homotechsual** [comment]
I'll fire it back into them too.
