### ISSUE TITLE
Error retrieving Organisation Documents 

### ISSUE THREAD

**Issue by TheFirstBold** [homotechsual/NinjaOne#16]
New-NinjaOneError: C:\Program Files\WindowsPowerShell\Modules\NinjaOne\1.3.0\Public\Get\Organisation\Get-NinjaOneOrganisationDocuments.ps1:37
Line |
  37 |          New-NinjaOneError -ErrorRecord $_
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The NinjaOne API said FAILURE: NullPointerException. The API returned the following HTTP error response: 500 Internal Server Error

**Comment by homotechsual** [comment]
Unfortunately a bug on Ninja's end when using client credentials authentication. Ninja are aware and working on it and a few others.

**Comment by TheFirstBold** [comment]
Probably the same issue as #11 
![image](https://user-images.githubusercontent.com/113010147/188811215-96fc142d-dd03-4a92-8edf-4d0df47c2ade.png)

**Comment by homotechsual** [comment]
Ninja confirmed 2022/08/31 that development are working on a fix for this.

**Comment by homotechsual** [comment]
Yes, this is working - thanks for the nudge :-D

Writing entirely new documents isn't currently supported but the API team are investigating!

**Comment by homotechsual** [comment]
More than happy to collaborate on this module unless you particularly want your own :-)

**Comment by xasz** [comment]
I will contribute If i can.. but for now i need ps5.1 Support and this Module cannot die that. I do Not  want to create New documents. Just Update Them, but i do Not understand the Push example on that in the Ninja Docs.Am 27.10.2022 16:58 schrieb homotechsual ***@***.***>:
More than happy to collaborate on this module unless you particularly want your own :-)
