### ISSUE TITLE
Get-NinjaOneUsers requires an Organisation ID

### ISSUE THREAD

**Issue by jsanzdev** [homotechsual/NinjaOne#18]
When using the functon Get-NinjaOneUsers it requires an Organisation ID. It Shouldn't be the case!

<img width="427" alt="image" src="https://user-images.githubusercontent.com/16939238/198651417-817ec0c7-156c-4165-8e99-66ee74899985.png">

**Comment by homotechsual** [comment]
Fixed with 7cd07b5f85679dd71076a24d39944c45bf464433
