### ISSUE TITLE
Invoke-NinjaOneRequest as a cmdlet.

### ISSUE THREAD

**Issue by Dope-Lemon** [homotechsual/NinjaOne#21]
I think what would make this great module even better is to add an ability to leverage the modules management of authorisation to make requests directly to the API. 

Ideally this would be similar to Invoke-MGGraphRequest listed here  [Microsoft Documentation](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-invoke-mggraphrequest)

With support for parameters such as -Method, -URI etc.

**Comment by homotechsual** [comment]
This is in 1.7.0 - though any missing cmdlets I'd like to know about so we can implement them directly too!
