### ISSUE TITLE
Invoke-NinjaOneDeviceScript

### ISSUE THREAD

**Issue by ADVTECH-AU** [homotechsual/NinjaOne#22]
Cant get this to work
But i seem to not be able to get it to work with the native api aswell.
I just want to call a script with powershell :(
Ie, call scripts within scripts

I get this with your module

```
Line |
  66 |          New-NinjaOneError -ErrorRecord $_
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The NinjaOne API said FAILURE: NullPointerException. The API returned the following HTTP error response: 500 Internal Server Error
```

And this with a Rest invoke

`Invoke-RestMethod: { "resultCode": "FAILURE", "errorMessage": "NullPointerException", "incidentId": "WEB_MGMT_SERVICE-2a-1683267369-FPCHHYPJ" }`

**Comment by homotechsual** [comment]
This is an intentional choice by Ninja not to allow that endpoint to be used unless authenticating interactively. You should feedback via your account manager or sales contact that you’d like to see it available for non interactive scenarios.
