### ISSUE TITLE
How to use update-ninjaonedevice?

### ISSUE THREAD

**Issue by tdrusk** [homotechsual/NinjaOne#24]
I have tried the following:

````
# Define the new device information
$deviceInformation = @{
    systemName = "Bob"
}

# Call the Update-NinjaOneDevice function
Update-NinjaOneDevice -deviceId 666 -deviceInformation $deviceInformation
```

but I get 

```
Get-NinjaOneDevice: The term 'Get-NinjaOneDevice' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I've also tried using friendlyName instead of SystemName, to the same result.

**Comment by homotechsual** [comment]
Yeah that is the latest - let me check briefly in case there's been a regression

**Comment by homotechsual** [comment]
So I've just checked the codebase and we have 0 calls to `Get-NinjaOneDevice` - we used to have an incorrect call in the update commandlet. can you try removing and reinstalling the module?

**Comment by tdrusk** [comment]
I did a uninstall-module ninjaone and then ran the install command. I am still getting 400 bad request. Can you provide an example code of what should be working? I just want to rename a PC.

**Comment by homotechsual** [comment]
Lemme test my end and come back to you :-)

**Comment by homotechsual** [comment]
So this works for me:

```ps
Update-NinjaOneDevice -deviceId 254 -deviceInformation @{ displayName = 'MikeyDesktop' }
```

![image](https://github.com/homotechsual/NinjaOne/assets/2288257/05c5e2ff-9a37-4839-b423-3cdd511dc33e)

**Comment by homotechsual** [comment]
The allowed body is documented here: https://eu.ninjarmm.com/apidocs-beta/core-resources/operations/updateDevice

**Comment by tdrusk** [comment]
Thanks for your help! It wasn't working, so I made a new API key and it worked so I must have messed that up somehow.
