### ISSUE TITLE
Problem with "Secure" custom fields "SECURE_VALUE_PLACEHOLDER_"

### ISSUE THREAD

**Issue by knoeblsn** [homotechsual/NinjaOne#30]
Hello, 

I have a problem with reading "secure" custom fields.

I have a custom field of type "Secure" in NinjaOne when I get the value from the custom field in Ninjaone, or with the ninjaone api the correct value is returned, when I get the value with the PowerShell module there is put "SECURE_VALUE_PLACEHOLDER_" in front of the value.

Example:
PS C:\Users\username> Get-NinjaOneDeviceCustomFields -deviceId "3316"
...
SecureCF        : SECURE_VALUE_PLACEHOLDER_asdabs-ioaoia-123123-asd
...

When I get the vaule via api "curl -X 'GET' \  'https://tennant.rmmservice.eu/v2/device/3316/custom-fields' \"
{
...
  "huduproxyauth": "asdabs-ioaoia-123123-asd",
...
}

In the NinjaOne Forum, I found an old thread mentioning the same placeholder, but I can not connect the dots myself.

Greetings, Stefan

**Comment by homotechsual** [comment]
You need to use Authorization Code to get custom field values. See the example here: https://docs.homotechsual.dev/modules/ninjaone/#connecting-to-ninjaone

If you need to do this in a longer-lasting way talk to your NinjaOne account manager and ask them to enable "Sliding Refresh Tokens" which means you can reuse your refresh token indefinitely (as long as you use it once every 14 days so it doesn't expire) to do something close to perpetual code auth using the Refresh Token flow documented here: https://docs.homotechsual.dev/modules/ninjaone/commandlets/connect/ninjaone#token-authentication

**Comment by knoeblsn** [comment]
Thanks for the Information. I will charge the authetication i am using in the Future. 
For the Moment i can change the CF to clear Text and work with that.
