### ISSUE TITLE
Get-NinjaOneTickets not returning any results

### ISSUE THREAD

**Issue by mattolan** [homotechsual/NinjaOne#31]
Public/Get/Ticketing/Get-NinjaOneTickets.ps1 returns no results for any of the sample queries.

After connecting I can query boards as expected. 

but "Get-NinjaOneTickets -boardId 2" returns nothing. boardID 2 is clearly valid
<img width="485" alt="Boards" src="https://github.com/homotechsual/NinjaOne/assets/67303446/fbef2d93-43e0-4ee1-bf23-7cae2e14fd95">

but 
 "Get-NinjaOneTickets -boardId 2"  returns nothing as does querying for a specific ticket "Get-NinjaOneTickets -ticketID 1317"
If I query for a ticket I know doesn't exist I get an error, but nothing is returned for a valid ticket.

<img width="866" alt="Tickets" src="https://github.com/homotechsual/NinjaOne/assets/67303446/1ee52dfe-7ce5-4dad-be6d-8d698c453323">

I tried release candidate 1.12.3 as well as the current prerelease version

**Comment by homotechsual** [comment]
Let me test this tomorrow and I'll sort out a fix!

**Comment by mattolan** [comment]
Thank you :-)

**Comment by homotechsual** [comment]
Identified the issue with boards and fixed.

**Comment by homotechsual** [comment]
Also found the ticket issue and fixed. Should get a new 2.x.x release out today.

**Comment by mattolan** [comment]
Thank you. It appears to be working now :-)

**Comment by mattolan** [comment]
Closing

**Comment by homotechsual** [comment]
Thanks for reporting and for your patience!
