### ISSUE TITLE
Get-NinjaOneActivities.ps1 only returns a single result

### ISSUE THREAD

**Issue by mattolan** [homotechsual/NinjaOne#33]
Get-NinjaOneActivities only returns a single result, instead of all results

**Comment by homotechsual** [comment]
Sorry, can't reproduce this. I get all results as expected.

**Comment by mattolan** [comment]
Ah,  I was thrown off by the single line returned... I see now the results are all in a .activities object on that single line

I can only seem to get a max 200 activities returned..  Is this by design? or is there another way to get a larger set of activities?

<img width="682" alt="All 200" src="https://github.com/homotechsual/NinjaOne/assets/67303446/df45929a-83cb-4fd8-b7e7-f1e732877463">

**Comment by homotechsual** [comment]
1. Use `-ExpandActivities` to automatically expand the activities property. https://docs.homotechsual.dev/modules/ninjaone/commandlets/get/activities#-expandactivities
2. Use `-PageSize` to increase the number of resources (max 1000). https://docs.homotechsual.dev/modules/ninjaone/commandlets/get/activities#-pagesize

**Comment by mattolan** [comment]
Thank you :-)
And thank you for this project :-) Its really amazing so far.  I stumbled on it by chance and it looks like it will be a godsend for working around the lack luster reporting in NinjaOne
