### ISSUE TITLE
Cannot bind argument to parameter 'Resource' because it is an empty string.

### ISSUE THREAD

**Issue by hpineapples** [homotechsual/NinjaOne#38]
In function 'Set-NinjaOneOrganisationPolicies', $Resource is not set, thus is null when the API call parameters are built later in the function, resulting in the error being thrown.

`$Resource = ("v2/organization/{0}/policies" -f $organisationId)`

Path from: https://app.ninjarmm.com/apidocs-beta/core-resources/operations/updateNodeRolePolicyAssignmentForOrganization

**Comment by homotechsual** [comment]
Thanks for that :rofl: it got removed during refactoring for v2. Knuckleheaded mistake.

**Comment by homotechsual** [comment]
Should go out in 2.0.0-RC5 which is due to release soon.
