### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by TammiBelcher** [homotechsual/NinjaOne#6]
I'm receiving the following error when executing connect-ninjaone.
 The NinjaOne API returned an error but did not provide a result code or error message. The API
     | returned the following HTTP error response:

This my RedirectUri in my Ninja Console:
https://Localhost:9090/*

I have attempted the configuration on two different computers with the same result.

Any help would be greatly appreciated. 

Thanks,
Tammi

**Comment by jomotechsual** [comment]
Hi Tammi,

Sorry - not sure why we didn't see this before! Can you test again with the updated version - we recommend using the `Client Credentials` authentication flow added in newer versions.
