### ISSUE TITLE
Successfully installed but all calls come up with New-NinjaOneError -ErrorRecord $_

### ISSUE THREAD

**Issue by Jarli01** [homotechsual/NinjaOne#9]
Hey thanks for maintaining this, I'm looking into using it but seem to be hitting a wall with a generic error of "New-NinjaOneError -ErrorRecord $_"

Regardless the module that I call (though I've randomly tested a few). 

Is there something specific I can check for that I may be missing? I am able to connect using the clientid and clientsecret, but on the page that loads I also get an error message there. .  Copied below. 

{ "resultCode": "FAILURE", "errorMessage": "HTTP 404 Not Found", "incidentId": "WEB_MGMT_SERVICE-2a-1654890304-TFZFNUTF" }

Hope you can help

**Comment by homotechsual** [comment]
404 sounds like it can't redirect you. What version do you have? `Get-Module NinjaOne`

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 E ***@***.***
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.
 
 
From: Dustin B ***@***.***>
Sent: Friday, June 10, 2022 8:45:42 PM
To: homotechsual/NinjaOne ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [homotechsual/NinjaOne] Successfully installed but all calls come up with New-NinjaOneError -ErrorRecord $_ (Issue #9)


Hey thanks for maintaining this, I'm looking into using it but seem to be hitting a wall with a generic error of "New-NinjaOneError -ErrorRecord $_"

Regardless the module that I call (though I've randomly tested a few).

Is there something specific I can check for that I may be missing? I am able to connect using the clientid and clientsecret, but on the page that loads I also get an error message there. . Copied below.

{ "resultCode": "FAILURE", "errorMessage": "HTTP 404 Not Found", "incidentId": "WEB_MGMT_SERVICE-2a-1654890304-TFZFNUTF" }

Hope you can help

**Comment by Jarli01** [comment]
1.2.3

![image](https://user-images.githubusercontent.com/14837699/173140003-813efe86-8aae-4954-b46b-4405ac8539bf.png)

**Comment by Jarli01** [comment]
For what its worth, I also get that 404 page when I log in directly with my API id and secret. . .

**Comment by homotechsual** [comment]
Without any secrets what does your `Connect-NinjaOne` look like?

**Comment by Jarli01** [comment]
I took from your how-to (obviously zeroing out the secrets)

```
$ConnectionParameters = @{
    instance = 'us'
    clientid = ''
    clientsecret = ''
    port = 9090
    UseWebAuth = $True
    ShowTokens = $True
    }
    Connect-NinjaOne @ConnectionParameters
```

**Comment by homotechsual** [comment]
What does your redirect URI look like in Ninja itself?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 E ***@***.***
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.

**Comment by Jarli01** [comment]
Am I a dope?

https://localhost

**Comment by homotechsual** [comment]
Should be `http://localhost:9090/`

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 E ***@***.***
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.

**Comment by Jarli01** [comment]
Testing now. .

**Comment by Jarli01** [comment]
Still getting that 404 page after attempting to connect-ninjaone

**Comment by Jarli01** [comment]
The specific URL address states 

`https://app.ninjarmm.com/ws/oauth/error?error=unauthorized_client&error_description=**Invalid+redirect_uri**`

Think this was a backend update?

**Comment by Jarli01** [comment]
I'll check back on this in a bit, have to head out. Thank you in advance for the help thus far!

**Comment by homotechsual** [comment]
Ninja seems to cache the old redirect URI for a time, make sure it's saved properly in Ninja as `http://localhost:9090/` if it is then just wait it out for an hour or so :-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 E ***@***.***
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.

**Comment by Jarli01** [comment]
Still getting this same 404 page after the weekend. . . . sorry

**Comment by homotechsual** [comment]
Can you share a screenshot of the application / client settings in Ninja?

**Comment by homotechsual** [comment]
Yes please :-)

**Comment by Jarli01** [comment]
![image](https://user-images.githubusercontent.com/14837699/173364152-39f1bc9b-0581-4372-b283-0cd13e602848.png)
![image](https://user-images.githubusercontent.com/14837699/173364214-dda72f5a-0ae1-4216-8f26-bd8642820acf.png)

See attached

**Comment by Jarli01** [comment]
Still getting a 404 after saving, I assume I should wait a bit and test again in an hour?

**Comment by homotechsual** [comment]
Can you try creating a new API application:

![image](https://user-images.githubusercontent.com/2288257/173365464-a0b3144a-d2a7-4a73-b479-b675cb11c069.png)

**Comment by Jarli01** [comment]
I get this with a new connection, using PS7 and

```
$ConnectionParameters = @{
    instance = 'us'
    clientid = 'Removed'
    clientsecret = 'removed'
    port = '9090'
    UseWebAuth = $True
    ShowTokens = $True
    }
    Connect-NinjaOne @ConnectionParameters
```

from website https://app.ninjarmm.com/ws/oauth/error?error=unauthorized_client&error_description=Invalid+redirect_uri 

{ "resultCode": "FAILURE", "errorMessage": "HTTP 404 Not Found", "incidentId": "WEB_MGMT_SERVICE-2a-1655127523-ACSIRYYU" }

**Comment by homotechsual** [comment]
That's back to "Invalid Redirect URI" which usually means the trailing `/` is missing or it's using `https` instead of `http`

**Comment by Jarli01** [comment]
Let me create a new on, using http://localhost:9090/ ( I didn't have the training / on it previously.

One moment and thank you for the help thus far

**Comment by homotechsual** [comment]
This helps me too - as we go I'm making notes to improve the documentation :-)

**Comment by Jarli01** [comment]
So brand new api connection I get redirected to `https://app.ninjarmm.com/ws/oauth/error?error=invalid_request&error_description=Invalid+scope+management+for+client`

and have error `{ "resultCode": "FAILURE", "errorMessage": "HTTP 404 Not Found", "incidentId": "WEB_MGMT_SERVICE-2a-1655128066-ZLTUGVPJ" }`

**Comment by homotechsual** [comment]
You'll have to adjust your connection parameters to:

```ps
$ConnectionParameters = @{
    instance = 'us'
    clientid = 'Removed'
    clientsecret = 'removed'
    port = '9090'
    scopes = @('monitoring','offline_access')
    UseWebAuth = $True
    ShowTokens = $True
}
Connect-NinjaOne @ConnectionParameters
```

**Comment by Jarli01** [comment]
Hazzaa we have a connection!

**Comment by homotechsual** [comment]
Awesome!

**Comment by Jarli01** [comment]
Ah so maybe that is to be expected . .  hrmm do you know what is included in monitoring so I can test? Anything offhand could work.

**Comment by Jarli01** [comment]
Although, I did just enable all settings on this API, updated the connection settings to include them and still get. . .

 `Get-NinjaOneActivities
New-NinjaOneError: C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Get\Entities\Get-NinjaOneActivities.ps1:72
Line |
  72 |          New-NinjaOneError -ErrorRecord $_
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The NinjaOne API said invalid_request. The API returned the following HTTP error response: 400 Bad
     | Request The API did not provide a response code or status.`

**Comment by homotechsual** [comment]
Can you share the output of `Get-Error`

**Comment by Jarli01** [comment]
`
Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'dotnet' is not recognized as a name of a cmdlet, function, script file, or executable
program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
            HResult : -2146233087
        TargetObject          : dotnet
        CategoryInfo          : ObjectNotFound: (dotnet:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 127
            OffsetInLine     : 59
            HistoryId        : 29
            ScriptName       :
C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1
            Line             : $Script:NRAPIAuthenticationInformation.Code = dotnet run --project
$OAuthListenerDirectory -- $Port

            PositionMessage  : At
C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1:127 char:59
                               + …          $Script:NRAPIAuthenticationInformation.Code = dotnet run --p …
                               +                                                          ~~~~~~
            PSScriptRoot     : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public
            PSCommandPath    :
C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1
            InvocationName   : dotnet
            CommandOrigin    : Internal
        ScriptStackTrace      : at Connect-NinjaOne,
C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1: line 127
                                at <ScriptBlock>, <No file>: line 1
    CommandName : dotnet
    TargetSite  :
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation,
Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'dotnet' is not recognized as a name of a cmdlet, function, script file, or executable
program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : dotnet
CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 127
    OffsetInLine     : 59
    HistoryId        : 29
    ScriptName       : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1
    Line             : $Script:NRAPIAuthenticationInformation.Code = dotnet run --project $OAuthListenerDirectory --
$Port

    PositionMessage  : At
C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1:127 char:59
                       + …          $Script:NRAPIAuthenticationInformation.Code = dotnet run --p …
                       +                                                          ~~~~~~
    PSScriptRoot     : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public
    PSCommandPath    : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1
    InvocationName   : dotnet
    CommandOrigin    : Internal
ScriptStackTrace      : at Connect-NinjaOne,
C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1: line 127
                        at <ScriptBlock>, <No file>: line 1

PS C:\Users\dbeuerlein>`

**Comment by homotechsual** [comment]
Looks like you're missing the dotnet SDK which runs the local webserver for auth so it's not authenticating properly/fully.

**Comment by homotechsual** [comment]
It needs .NET 6 - the runtime should be fine but it might want the SDK.

**Comment by Jarli01** [comment]
Downloading now

**Comment by Jarli01** [comment]
So installed 6.0 SDK and visual studio (community) am getting

	PS C:\Users\dbeuerlein> get-error

	Exception             :
		Type       : Microsoft.PowerShell.Commands.HttpResponseException
		Response   : StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content:
	System.Net.Http.HttpConnectionResponseContent, Headers:
					 {
					 Date: Mon, 13 Jun 2022 14:08:41 GMT
					 Connection: keep-alive
					 Server: nginx
					 Cache-Control: no-store
					 Vary: Accept-Encoding
					 Content-Type: application/json
					 Content-Length: 27
					 }, Trailing Headers:
					 {
					 }
		TargetSite :
			Name          : ThrowTerminatingError
			DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation,
	Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
			MemberType    : Method
			Module        : System.Management.Automation.dll
		Message    : Response status code does not indicate success: 400 (Bad Request).
		Source     : System.Management.Automation
		HResult    : -2146233088
		StackTrace :
	   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
	TargetObject          : Method: POST, RequestUri: 'https://app.ninjarmm.com/oauth/token', Version: 1.1, Content:
	System.Net.Http.ByteArrayContent, Headers:
							{
							User-Agent: Mozilla/5.0
							User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.19044; en-US)
							User-Agent: PowerShell/7.2.4
							Content-Length: 197
							Content-Type: application/x-www-form-urlencoded
							}
	CategoryInfo          : InvalidOperation: (Method: POST, Reque…-form-urlencoded
							}:HttpRequestMessage) [New-NinjaOneError], HttpResponseException
	FullyQualifiedErrorId : WebCmdletWebResponseException,New-NinjaOneError
	ErrorDetails          : The NinjaOne API said invalid_request. The API returned the following HTTP error response: 400
	Bad Request
							The API did not provide a response code or status.
	InvocationInfo        :
		MyCommand        : New-NinjaOneError
		ScriptLineNumber : 72
		OffsetInLine     : 9
		HistoryId        : 38
		ScriptName       :
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Get\Entities\Get-NinjaOneActivities.ps1
		Line             : New-NinjaOneError -ErrorRecord $_

		PositionMessage  : At
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Get\Entities\Get-NinjaOneActivities.ps1:72
	char:9
						   +         New-NinjaOneError -ErrorRecord $_
						   +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		PSScriptRoot     : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Get\Entities
		PSCommandPath    :
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Get\Entities\Get-NinjaOneActivities.ps1
		InvocationName   : New-NinjaOneError
		CommandOrigin    : Internal
	ScriptStackTrace      : at Connect-NinjaOne,
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1: line 179
							at Update-NinjaOneToken,
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Private\Update-NinjaOneToken.ps1: line 16
							at Invoke-NinjaOneRequest,
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Private\Invoke-NinjaOneRequest.ps1: line 26
							at New-NinjaOneGETRequest,
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Private\New-NinjaOneGETRequest.ps1: line 49
							at Get-NinjaOneActivities,
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Get\Entities\Get-NinjaOneActivities.ps1: line 69
							at <ScriptBlock>, <No file>: line 1

Assuming a reboot may be required?

**Comment by homotechsual** [comment]
Try running the `Connect-NinjaOne` command again.

**Comment by Jarli01** [comment]
On reconnect (post reboot) I got 

	PS C:\Users\dbeuerlein>     Connect-NinjaOne @ConnectionParameters

	The build failed. Fix the build errors and run again.
	Invoke-WebRequest: C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1:179
	Line |
	 179 |              $TokenResult = Invoke-WebRequest @TokenRequestParams
		 |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		 | {"error":"invalid_token"}


I'm getting the below on Get-Error

	PS C:\Users\dbeuerlein> get-error

	Exception             :
		Type       : Microsoft.PowerShell.Commands.HttpResponseException
		Response   : StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content:
	System.Net.Http.HttpConnectionResponseContent, Headers:
					 {
					 Date: Mon, 13 Jun 2022 14:42:27 GMT
					 Connection: keep-alive
					 Server: nginx
					 Cache-Control: no-store
					 Vary: Accept-Encoding
					 Content-Type: application/json
					 Content-Length: 25
					 }
		TargetSite :
			Name          : ThrowTerminatingError
			DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation,
	Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
			MemberType    : Method
			Module        : System.Management.Automation.dll
		Message    : Response status code does not indicate success: 400 (Bad Request).
		Source     : System.Management.Automation
		HResult    : -2146233088
		StackTrace :
	   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
	TargetObject          : Method: POST, RequestUri: 'https://app.ninjarmm.com/oauth/token', Version: 1.1, Content:
	System.Net.Http.ByteArrayContent, Headers:
							{
							User-Agent: Mozilla/5.0
							User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.19044; en-US)
							User-Agent: PowerShell/7.2.4
							Content-Length: 239
							Content-Type: application/x-www-form-urlencoded
							}
	CategoryInfo          : InvalidOperation: (Method: POST, Reque…-form-urlencoded
							}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
	FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
	ErrorDetails          : {"error":"invalid_token"}
	InvocationInfo        :
		MyCommand        : Invoke-WebRequest
		ScriptLineNumber : 179
		OffsetInLine     : 28
		HistoryId        : 2
		ScriptName       : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1
		Line             : $TokenResult = Invoke-WebRequest @TokenRequestParams

		PositionMessage  : At
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1:179 char:28
						   +             $TokenResult = Invoke-WebRequest @TokenRequestParams
						   +                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		PSScriptRoot     : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public
		PSCommandPath    : C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1
		InvocationName   : Invoke-WebRequest
		CommandOrigin    : Internal
	ScriptStackTrace      : at Connect-NinjaOne,
	C:\Users\dbeuerlein\Documents\PowerShell\Modules\NinjaOne\1.2.3\Public\Connect-NinjaOne.ps1: line 179
							at <ScriptBlock>, <No file>: line 1

**Comment by homotechsual** [comment]
So definitely a `.NET` issue with the little web server. Can you try the `client_credentials` authentication flow.

```ps
$ConnectionParameters = @{
    instance = 'us'
    clientid = 'Removed'
    clientsecret = 'removed'
    scopes = @('monitoring','offline_access')
    UseClientAuth = $True
    ShowTokens = $True
}
Connect-NinjaOne @ConnectionParameters
```

**Comment by Jarli01** [comment]
With that I get 

`Connect-NinjaOne: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.`

But I'm getting sidebarred by the day and will have to come back to this in a bit. Thanks!

**Comment by Jarli01** [comment]
I think I'm all set to start getting some scripts going. Hope this helped to sort out any future troubleshooting.

**Comment by homotechsual** [comment]
just checking your redirect URI in Ninja now has the port, http and the trailing `/`

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 E ***@***.***
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.
